name: Docker Image CI

on:
  push:
    #branches: [ main ]
    tags:
      - '*.*'
  #pull_request: ~
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Set the tags value
      id: step_one
      run: |
        echo "DOCKER_REG=docker.io/${{ secrets.USERNAME }}/iammeter-simulator" >> $GITHUB_ENV
        # echo name=VERSION::${GITHUB_REF/refs\/tags\//} >> $GITHUB_ENV
        echo VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_ENV
    - name: Use the tags value
      id: step_two
      run: |
        echo "${{ env.DOCKER_REG }}" # This will output ''
        # echo "${{ env.name }}" # This will output 'VERSION::1.0'
        echo "${{ env.VERSION }}" # This will output '1.0'
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.DOCKER_REG }}:${{ env.VERSION }}, ${{ env.DOCKER_REG }}:latest  
